# Generated by Django 3.1.1 on 2020-09-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
