# Generated by Django 3.1.1 on 2020-09-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200910_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
    ]
